/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { PerspectiveCamera, useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/4CAM.glb') as any
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera
        makeDefault={true} // Đặt camera này làm camera chính
        far={3000} // Thay đổi giá trị far
        near={0.5} // Thay đổi giá trị near
        fov={15} // Thay đổi giá trị fov
        position={[-1000, 800, -1400]} // Thay đổi vị trí camera
        rotation={[0, -400, 300]} // Thay đổi góc quay camera
        scale={[1, 1, 1]} // Thay đổi tỷ lệ camera
      />
      <spotLight
        intensity={43333.277}
        angle={1.49}
        penumbra={1}
        decay={2}
        distance={6210.945}
        position={[730.144, 135.721, -106.036]}
        rotation={[-1.962, 1.356, 2.461]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={576.169}
        near={0.1}
        fov={2864.789}
        position={[-391.883, -345.483, 1019.515]}
        rotation={[0.074, 0.618, 0.008]}
        scale={[-1.836, 2.138, 1.502]}
      />
      <spotLight
        intensity={35677.781}
        angle={Math.PI / 4}
        penumbra={1}
        decay={2}
        distance={18410.609}
        position={[-389.093, 1065.723, 37.324]}
        rotation={[-1.548, -0.343, -1.564]}
      />
      <spotLight
        intensity={146235.594}
        angle={1.017}
        penumbra={1}
        decay={2}
        distance={45005.945}
        position={[344.319, 315.533, -1350.661]}
        rotation={[-2.935, 0.067, -3.123]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1442.845}
        near={0.1}
        fov={1543.019}
        position={[-578.643, -429.502, 1666.512]}
        rotation={[-0.389, 0.327, 0.029]}
        scale={[-4.063, 4, 1.837]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={2864.789}
        position={[-24.474, -249.055, 2613.42]}
        rotation={[-0.239, 0.461, 0.002]}
        scale={[-2, 2.099, 1.339]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube4.geometry}
        material={materials.blinn8SG}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface106_polySurface70.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface107.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface105.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface90_polySurface58.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface93.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface114.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface99_polySurface68.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface76_polySurface69.geometry}
        material={materials.blinn3SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface110.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface75.geometry}
        material={materials.blinn6SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface91.geometry}
        material={materials.pasted__blinn4SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface86.geometry}
        material={materials.blinn6SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface95.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface96.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface98.geometry}
        material={materials.blinn3SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface104.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface103.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface72.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface100.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface102.geometry}
        material={materials.pasted__blinn4SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface87.geometry}
        material={materials.blinn3SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface101.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface113.geometry}
        material={materials.pasted__blinn4SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface73.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface77.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface112.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface89.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface115.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface82.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface92.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface81.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface85.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface78.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface108.geometry}
        material={materials.blinn6SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface80.geometry}
        material={materials.pasted__blinn4SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface109.geometry}
        material={materials.blinn3SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface70_polySurface111.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface94.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface84.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface68_polySurface97.geometry}
        material={materials.blinn6SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface74.geometry}
        material={materials.pasted__blinn1SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface88.geometry}
        material={materials.pasted__blinn5SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface58_polySurface83.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.polySurface69_polySurface79.geometry}
        material={materials.pasted__blinn2SG}
        rotation={[0, 0, 0]}
        position={[0, 0, 0]}
        scale={[1, 1, 1]}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={2578.31}
        position={[-323.086, -192.96, 1141.955]}
        rotation={[-0.288, 0.014, 0.001]}
        scale={[-2.414, 2.366, 1.109]}
      />
      <spotLight
        intensity={26595.701}
        angle={0.873}
        penumbra={1}
        decay={2}
        distance={11116.467}
        position={[-1058.528, 23.872, 500.537]}
        rotation={[-0.084, -1.135, -0.076]}
      />
      <spotLight
        intensity={103127.992}
        angle={0.873}
        penumbra={1}
        decay={2}
        distance={43105.422}
        position={[6.408, -3361.931, -48.931]}
        rotation={[1.579, -0.013, 2.117]}
      />
      <spotLight
        intensity={99963.289}
        angle={2.094}
        penumbra={1}
        decay={2}
        distance={7253.931}
        position={[-539.03, 272.858, -396.906]}
        rotation={[3.097, -0.655, -2.634]}
      />
    </group>
  )
}

useGLTF.preload('/models/4CAM.glb')
